### ISSUE TITLE
Latest versions

### ISSUE THREAD

**Issue by sirdrug** [SIDN/hadoop-provisioning-manager#4]
Hi! Is it posible to run you manager on latest version OS like Ubuntu 22.04?
What about updates of components hadoop?

**Comment by mwullink** [comment]
Hi,

Ubuntu 22.04 should also work fine but is not tested, if you do run into any problems, just let me know and i’ll see if i can fix it.

**Comment by sirdrug** [comment]
I prepare hosts like describe in readme and have many errors. May be do something wrong. I try with Ubuntu 20.04

**Comment by mwullink** [comment]
what is the error?

**Comment by sirdrug** [comment]
for example:
do not set password for user postgres, manualy passowrd set correctly. Task execute with no errors
, but password not set. When deploy.sh all is executed, hosts are not correctly selected everywhere, for example, zookeper, while if deploy.sh zookeeper is executed, everything is fine
